'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  Form,
  Input,
  InputNumber,
  Button,
  Card,
  Row,
  Col,
  Select,
  Switch,
  Space,
  message,
  Divider,
  Typography,
} from 'antd';
import { SaveOutlined, ArrowLeftOutlined, PlusOutlined, DeleteOutlined } from '@ant-design/icons';
import { useAppSelector } from '@/stores/hooks';
import { isSuperuser } from '@/shared/utils/permissions';
import {
  useCreateProduct,
  useCategories,
  useColors,
  useSizes,
  useTags,
  useCreateTag,
} from '../_api';
import type { CreateProductRequest } from '../_api';
import { useQueryClient } from '@tanstack/react-query';

const { TextArea } = Input;
const { Title } = Typography;
const { Option } = Select;

// Helper function to generate slug from title
const generateSlug = (title: string): string => {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
};

export default function NewProductPage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const { user } = useAppSelector((state) => state.auth);
  const [form] = Form.useForm<CreateProductRequest>();
  const createProductMutation = useCreateProduct();
  const createTagMutation = useCreateTag();
  const { data: categories = [], isLoading: categoriesLoading } = useCategories();
  const { data: colors = [], isLoading: colorsLoading } = useColors();
  const { data: sizes = [], isLoading: sizesLoading } = useSizes();
  const { data: tagsData = [], isLoading: tagsLoading } = useTags();

  const [thumbnailUrl, setThumbnailUrl] = useState<string>('');
  const [features, setFeatures] = useState<string[]>(['']);
  const [specs, setSpecs] = useState<Array<{ key: string; value: string }>>([
    { key: '', value: '' },
  ]);
  const [tags, setTags] = useState<string[]>([]);

  const canCreateTags = isSuperuser(user);

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const title = e.target.value;
    const slug = generateSlug(title);
    form.setFieldsValue({ slug });
  };

  const handleSubmit = async (values: CreateProductRequest) => {
    try {
      // Prepare data - slug will be generated by backend from title
      const productData: CreateProductRequest = {
        ...values,
        slug: generateSlug(values.title), // Generate slug from title (backend will also generate it)
        thumbnail: thumbnailUrl || values.thumbnail,
        features: features.filter((f) => f.trim() !== ''),
        specs: specs
          .filter((s) => s.key.trim() !== '' && s.value.trim() !== '')
          .map((s, index) => ({
            key: s.key,
            value: s.value,
            order: index,
          })),
        tags: tags.filter((t) => t.trim() !== ''),
      };

      await createProductMutation.mutateAsync(productData);
      message.success('محصول با موفقیت ایجاد شد');
      router.push('/admin/products');
    } catch (error: any) {
      message.error(error?.response?.data?.message || 'خطا در ایجاد محصول');
    }
  };

  const addFeature = () => {
    setFeatures([...features, '']);
  };

  const removeFeature = (index: number) => {
    setFeatures(features.filter((_, i) => i !== index));
  };

  const updateFeature = (index: number, value: string) => {
    const newFeatures = [...features];
    newFeatures[index] = value;
    setFeatures(newFeatures);
  };

  const addSpec = () => {
    setSpecs([...specs, { key: '', value: '' }]);
  };

  const removeSpec = (index: number) => {
    setSpecs(specs.filter((_, i) => i !== index));
  };

  const updateSpec = (index: number, field: 'key' | 'value', value: string) => {
    const newSpecs = [...specs];
    newSpecs[index][field] = value;
    setSpecs(newSpecs);
  };

  return (
    <div className="container mx-auto py-6">
      <Space direction="vertical" size="large" className="w-full">
        {/* Header */}
        <div className="flex items-center justify-between">
          <Title level={2} className="mb-0!">
            افزودن محصول جدید
          </Title>
          <Button icon={<ArrowLeftOutlined />} onClick={() => router.push('/admin/products')}>
            بازگشت
          </Button>
        </div>

        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmit}
          initialValues={{
            discount: 0,
            stock: 0,
            price: 0,
            is_new: false,
            is_featured: false,
          }}
        >
          <Row gutter={[16, 16]}>
            {/* Basic Information */}
            <Col xs={24}>
              <Card title="اطلاعات پایه" className="mb-4">
                <Row gutter={[16, 16]}>
                  <Col xs={24} md={12}>
                    <Form.Item
                      name="title"
                      label="عنوان محصول"
                      rules={[
                        { required: true, message: 'عنوان محصول الزامی است' },
                        { min: 3, message: 'عنوان باید حداقل ۳ کاراکتر باشد' },
                      ]}
                    >
                      <Input placeholder="عنوان محصول" onChange={handleTitleChange} />
                    </Form.Item>
                  </Col>

                  <Col xs={24} md={12}>
                    <Form.Item
                      name="slug"
                      label="Slug (خودکار از عنوان تولید می‌شود)"
                      rules={[
                        { required: true, message: 'Slug الزامی است' },
                        { min: 3, message: 'Slug باید حداقل ۳ کاراکتر باشد' },
                      ]}
                    >
                      <Input placeholder="slug-product" disabled className="bg-gray-50" />
                    </Form.Item>
                  </Col>

                  <Col xs={24} md={12}>
                    <Form.Item
                      name="brand"
                      label="برند"
                      rules={[
                        { required: true, message: 'برند الزامی است' },
                        { min: 2, message: 'برند باید حداقل ۲ کاراکتر باشد' },
                      ]}
                    >
                      <Input placeholder="نام برند" />
                    </Form.Item>
                  </Col>

                  <Col xs={24} md={12}>
                    <Form.Item
                      name="thumbnail"
                      label="آدرس تصویر شاخص"
                      rules={[{ required: true, message: 'تصویر شاخص الزامی است' }]}
                    >
                      <Input
                        placeholder="https://example.com/image.jpg"
                        value={thumbnailUrl}
                        onChange={(e) => setThumbnailUrl(e.target.value)}
                      />
                    </Form.Item>
                  </Col>

                  <Col xs={24}>
                    <Form.Item
                      name="short_description"
                      label="توضیحات کوتاه"
                      rules={[
                        {
                          max: 500,
                          message: 'توضیحات کوتاه نباید بیشتر از ۵۰۰ کاراکتر باشد',
                        },
                      ]}
                    >
                      <TextArea
                        rows={3}
                        placeholder="توضیحات کوتاه محصول (حداکثر ۵۰۰ کاراکتر)"
                        maxLength={500}
                        showCount
                      />
                    </Form.Item>
                  </Col>

                  <Col xs={24}>
                    <Form.Item
                      name="description"
                      label="توضیحات کامل"
                      rules={[
                        {
                          min: 10,
                          message: 'توضیحات باید حداقل ۱۰ کاراکتر باشد',
                        },
                      ]}
                    >
                      <TextArea rows={6} placeholder="توضیحات کامل محصول" />
                    </Form.Item>
                  </Col>
                </Row>
              </Card>
            </Col>

            {/* Categories and Pricing */}
            <Col xs={24} md={12}>
              <Card title="دسته‌بندی و قیمت‌گذاری" className="mb-4">
                <Space direction="vertical" size="middle" className="w-full">
                  <Form.Item
                    name="categories"
                    label="دسته‌بندی‌ها"
                    rules={[
                      {
                        required: true,
                        message: 'حداقل یک دسته‌بندی الزامی است',
                      },
                    ]}
                  >
                    <Select
                      mode="multiple"
                      placeholder="انتخاب دسته‌بندی"
                      loading={categoriesLoading}
                      showSearch
                      filterOption={(input, option) => {
                        const label = option?.label || option?.children;
                        return String(label || '')
                          .toLowerCase()
                          .includes(input.toLowerCase());
                      }}
                    >
                      {categories.map((cat) => (
                        <Option key={cat.id} value={cat.id}>
                          {cat.name}
                        </Option>
                      ))}
                    </Select>
                  </Form.Item>

                  <Form.Item
                    name="price"
                    label="قیمت (تومان)"
                    rules={[
                      { required: true, message: 'قیمت الزامی است' },
                      { type: 'number', min: 0, message: 'قیمت باید مثبت باشد' },
                    ]}
                  >
                    <InputNumber
                      className="w-full"
                      placeholder="قیمت محصول"
                      formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
                      parser={(value) => value!.replace(/\$\s?|(,*)/g, '') as any}
                    />
                  </Form.Item>

                  <Form.Item name="origin_price" label="قیمت اصلی (تومان)">
                    <InputNumber
                      className="w-full"
                      placeholder="قیمت اصلی (قبل از تخفیف)"
                      formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
                      parser={(value) => value!.replace(/\$\s?|(,*)/g, '') as any}
                    />
                  </Form.Item>

                  <Form.Item
                    name="discount"
                    label="تخفیف (%)"
                    rules={[
                      { type: 'number', min: 0, max: 100, message: 'تخفیف باید بین ۰ تا ۱۰۰ باشد' },
                    ]}
                  >
                    <InputNumber className="w-full" placeholder="درصد تخفیف" min={0} max={100} />
                  </Form.Item>

                  <Form.Item
                    name="stock"
                    label="موجودی"
                    rules={[
                      { required: true, message: 'موجودی الزامی است' },
                      { type: 'number', min: 0, message: 'موجودی باید مثبت باشد' },
                    ]}
                  >
                    <InputNumber className="w-full" placeholder="تعداد موجود" min={0} />
                  </Form.Item>
                </Space>
              </Card>
            </Col>

            {/* Colors, Sizes, and Options */}
            <Col xs={24} md={12}>
              <Card title="رنگ‌ها، سایزها و گزینه‌ها" className="mb-4">
                <Space direction="vertical" size="middle" className="w-full">
                  <Form.Item name="colors" label="رنگ‌ها">
                    <Select
                      mode="multiple"
                      placeholder="انتخاب رنگ‌ها"
                      loading={colorsLoading}
                      showSearch
                      filterOption={(input, option) => {
                        const label = option?.label || option?.children;
                        return String(label || '')
                          .toLowerCase()
                          .includes(input.toLowerCase());
                      }}
                    >
                      {colors.map((color) => (
                        <Option key={color.id} value={color.id}>
                          <Space>
                            <div
                              style={{
                                width: 16,
                                height: 16,
                                backgroundColor: color.hex,
                                border: '1px solid #ddd',
                                borderRadius: 4,
                                display: 'inline-block',
                              }}
                            />
                            {color.name}
                          </Space>
                        </Option>
                      ))}
                    </Select>
                  </Form.Item>

                  <Form.Item name="sizes" label="سایزها">
                    <Select
                      mode="multiple"
                      placeholder="انتخاب سایزها"
                      loading={sizesLoading}
                      showSearch
                      filterOption={(input, option) => {
                        const label = option?.label || option?.children;
                        return String(label || '')
                          .toLowerCase()
                          .includes(input.toLowerCase());
                      }}
                    >
                      {sizes.map((size) => (
                        <Option key={size.id} value={size.id}>
                          {size.name}
                        </Option>
                      ))}
                    </Select>
                  </Form.Item>

                  <Form.Item name="tags" label="تگ‌ها">
                    <Select
                      mode="tags"
                      placeholder={
                        canCreateTags
                          ? 'انتخاب یا افزودن تگ (Enter برای افزودن به دیتابیس)'
                          : 'انتخاب تگ'
                      }
                      tokenSeparators={[',']}
                      value={tags}
                      onChange={setTags}
                      loading={tagsLoading || createTagMutation.isPending}
                      showSearch
                      filterOption={(input, option) => {
                        const label = option?.label || option?.children;
                        return String(label || '')
                          .toLowerCase()
                          .includes(input.toLowerCase());
                      }}
                      onInputKeyDown={async (e) => {
                        // Handle Enter key for superuser
                        if (canCreateTags && e.key === 'Enter') {
                          const input = e.currentTarget as HTMLInputElement;
                          const value = input.value?.trim();
                          if (
                            value &&
                            !tags.includes(value) &&
                            !tagsData.some((t) => t.name === value)
                          ) {
                            e.preventDefault();
                            // Create tag
                            try {
                              const newTag = await createTagMutation.mutateAsync(value);
                              // Refresh tags list
                              await queryClient.invalidateQueries({ queryKey: ['admin', 'tags'] });
                              // Add to tags
                              setTags([...tags, newTag.name]);
                              message.success(`تگ "${value}" با موفقیت ایجاد شد`);
                            } catch (error: any) {
                              message.error(error?.response?.data?.message || 'خطا در ایجاد تگ');
                            }
                          }
                        }
                      }}
                    >
                      {tagsData.map((tag) => (
                        <Option key={tag.id} value={tag.name}>
                          {tag.name}
                        </Option>
                      ))}
                    </Select>
                  </Form.Item>

                  <Divider />

                  <Form.Item name="is_new" label="محصول جدید" valuePropName="checked">
                    <Switch />
                  </Form.Item>

                  <Form.Item name="is_featured" label="محصول ویژه" valuePropName="checked">
                    <Switch />
                  </Form.Item>
                </Space>
              </Card>
            </Col>

            {/* Features */}
            <Col xs={24}>
              <Card title="ویژگی‌ها" className="mb-4">
                <Space direction="vertical" size="middle" className="w-full">
                  {features.map((feature, index) => (
                    <Space key={index} className="w-full">
                      <Input
                        placeholder="ویژگی محصول"
                        value={feature}
                        onChange={(e) => updateFeature(index, e.target.value)}
                        className="flex-1"
                      />
                      {features.length > 1 && (
                        <Button
                          type="text"
                          danger
                          icon={<DeleteOutlined />}
                          onClick={() => removeFeature(index)}
                        />
                      )}
                    </Space>
                  ))}
                  <Button type="dashed" icon={<PlusOutlined />} onClick={addFeature} block>
                    افزودن ویژگی
                  </Button>
                </Space>
              </Card>
            </Col>

            {/* Specs */}
            <Col xs={24}>
              <Card title="مشخصات فنی" className="mb-4">
                <Space direction="vertical" size="middle" className="w-full">
                  {specs.map((spec, index) => (
                    <Row key={index} gutter={8} align="middle">
                      <Col xs={10}>
                        <Input
                          placeholder="نام مشخصه"
                          value={spec.key}
                          onChange={(e) => updateSpec(index, 'key', e.target.value)}
                        />
                      </Col>
                      <Col xs={12}>
                        <Input
                          placeholder="مقدار"
                          value={spec.value}
                          onChange={(e) => updateSpec(index, 'value', e.target.value)}
                        />
                      </Col>
                      <Col xs={2}>
                        {specs.length > 1 && (
                          <Button
                            type="text"
                            danger
                            icon={<DeleteOutlined />}
                            onClick={() => removeSpec(index)}
                          />
                        )}
                      </Col>
                    </Row>
                  ))}
                  <Button type="dashed" icon={<PlusOutlined />} onClick={addSpec} block>
                    افزودن مشخصه
                  </Button>
                </Space>
              </Card>
            </Col>

            {/* Submit Buttons */}
            <Col xs={24}>
              <Card>
                <Space>
                  <Button
                    type="primary"
                    htmlType="submit"
                    icon={<SaveOutlined />}
                    loading={createProductMutation.isPending}
                    size="large"
                  >
                    ایجاد محصول
                  </Button>
                  <Button onClick={() => router.push('/admin/products')} size="large">
                    انصراف
                  </Button>
                </Space>
              </Card>
            </Col>
          </Row>
        </Form>
      </Space>
    </div>
  );
}
